config/routes.rb
Rails.application.routes.draw do
  
  resources :customers
  resources :medicines
  resources :prescriptions
  
  root 'customers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    paginates_per 10
end

app/models/disease.rb
class Disease < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  belongs_to :medicine_category
end

app/models/medicine_category.rb
class MedicineCategory < ApplicationRecord
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :customer
  has_many :prescription_diseases
  has_many :diseases, through :prescription_diseases

  has_many :prescription_medicines
  has_many :medicines, through :prescription_medicines
end

app/models/prescription_disease.rb
class PrescriptionDisease < ApplicationRecord
  belongs_to :disease
  belongs_to :prescription
end

app/models/prescription_medicine.rb
class PrescriptionMedicine < ApplicationRecord
  belongs_to :medicine
  belongs_to :prescription
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.order(:name).page params[:page]
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.create(params)
  end

  def destroy
  end


  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find params[:id]
    res = @customer.update customer_params
    if res
      flash.now[:notice] = "You have updated customer successfully"
      redirect_to customers_path
      # render 'index'
    end
  end

  private 
  def customer_params
    params.require(:customer).permit(:name, :id_card, :dob, :pob, :phone_number, :address, :email, :gender, :description)
  end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  def index
    @medicines = Medicine.includes(:medicine_category).first(20)
  end

  def show
    @medicine = Medicine.find params[:id]
  end

  def new
    @medicine = Medicine.new
  end

  def create
    @medicine = Medicine.create medicine_params
    if @medicine
      flash[:notice] = "Yay, medicine created successfully"
      redirect_to medicines_path
    end
  end

  def edit
    @medicine = Medicine.find params[:id]
  end

  def update
    @medicine = Medicine.find params[:id]
    @medicine.update(medicine_params)
    flash[:notice] = "You have updated this medicine successfully"
    redirect_to medicine_path
  end

  def destroy
  end

  private 
  def medicine_params
    params.require(:medicine).permit(:name, :price, :unit, :medicine_category_id, :use, :description)
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => "form-horizontal customer" } do |f| %>

  <% if @customer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :id_card, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :id_card, :class => 'form-control' %>
    </div>
    <%=f.error_span(:id_card) %>
  </div>
  <div class="form-group">
    <%= f.label :dob, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%# f.text_field :dob, :class => 'form-control' %>
      <%= f.date_field :dob, :class => 'form-control' %>
    </div>
    <%=f.error_span(:dob) %>
  </div>
  <div class="form-group">
    <%= f.label :pob, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :pob, :class => 'form-control' %>
    </div>
    <%=f.error_span(:pob) %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone_number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone_number) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.email_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :gender, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%# f.text_field :gender, :class => 'form-control' %>
      <%= select_tag :gender, options_for_select([['Male', 'M'], ['Female', 'F']]), :class => 'form-control' %>
    </div>
    <%=f.error_span(:gender) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

app/views/customers/destroy.html.erb
<h1>Customers#destroy</h1>
<p>Find me in app/views/customers/destroy.html.erb</p>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/index.html.erb
<% model_class = Customer %>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<div>
<%= paginate @customers, window: 1, outer_window: 1  %>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:id_card) %></th>
      <th><%= model_class.human_attribute_name(:dob) %></th>
      <th><%= model_class.human_attribute_name(:pob) %></th>
      <th><%= model_class.human_attribute_name(:phone_number) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.name, customer_path(customer) %></td>
        <td><%= customer.id_card %></td>
        <td><%= customer.dob %></td>
        <td><%= customer.pob %></td>
        <td><%= customer.phone_number %></td>
        <td><%= customer.address %></td>
        <td><%= customer.email %></td>
        <td><%= customer.gender %></td>
        <td><%= customer.description %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      customer_path(customer), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_path(customer), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= paginate @customers, window: 1, outer_window: 1  %>

app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @customer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:id_card) %>:</strong></dt>
  <dd><%= @customer.id_card %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dob) %>:</strong></dt>
  <dd><%= @customer.dob %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pob) %>:</strong></dt>
  <dd><%= @customer.pob %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone_number) %>:</strong></dt>
  <dd><%= @customer.phone_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @customer.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @customer.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
  <dd><%= @customer.gender %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @customer.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplePharmacy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= nav_bar brand: "Simple Pharmacy", fixed: :top, responsive: true do %>
      <%= menu_group do %>
            <%= menu_item "Customer", customers_path %>
            <%= menu_item "Medicines", medicines_path %>
        <% end %>
    <% end %>
    <div class="page-body">
    <%= render 'shared/flash' %>
    <%= yield %>
    </div>
    <div class="page-bottom"></div>
    </div>
  </body>
</html>

app/views/medicines/_form.html.erb
<%= form_for @medicine, :html => { :class => "form-horizontal medicine" } do |f| %>

  <% if @medicine.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@medicine.errors.count, "error") %> prohibited this medicine from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @medicine.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label 'price (1000 VND)', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :unit, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select_tag :unit,  options_for_select(['Hop', 'Lo', 'Chai']),  :class => 'form-control' %>
    </div>
    <%=f.error_span(:unit) %>
  </div>
  <div class="form-group">
    <%= f.label :medicine_category_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select(:medicine_category_id, MedicineCategory.all, :id, :name, {}, {:class => 'form-control'}) %>
    </div>
    <%=f.error_span(:medicine_category_id) %>
  </div>
  <div class="form-group">
    <%= f.label :use, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :use, :class => 'form-control' %>
    </div>
    <%=f.error_span(:use) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                medicines_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/medicines/destroy.html.erb
<h1>Medicines#destroy</h1>
<p>Find me in app/views/medicines/destroy.html.erb</p>

app/views/medicines/edit.html.erb
<%- model_class = Medicine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/medicines/index.html.erb
<% model_class = Medicine %>
<div class="page-header">

<%= link_to t('.new', :default => t("helpers.links.new")), new_medicine_path, class: 'btn btn-primary' %>
<table class="table table-striped">
<thead>
<tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:price) %></th>
    <th><%= model_class.human_attribute_name(:unit) %></th>
    <th><%= model_class.human_attribute_name(:medicine_category_id) %></th>
    <th><%= model_class.human_attribute_name(:use) %></th>
    <th><%= model_class.human_attribute_name(:description) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
</tr>
</thead>
<tbody>
    <% @medicines.each do |medicine| %>
    <tr>
        <th> <%= link_to medicine.id , medicine_path(medicine) %></th>
        <th><%= medicine.name %></th>
        <th><%= medicine.price %></th>
        <th><%= medicine.unit %></th>
        <th><%= medicine.medicine_category.name %></th>
        <th><%= medicine.use %></th>
        <th><%= medicine.description %></th>
        <th>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        medicine_path(medicine), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_medicine_path(medicine), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      medicine_path(medicine),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </th>
    </tr>
    <% end %>
</tbody>
</table>

</div>

app/views/medicines/new.html.erb
<%- model_class = Medicine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/medicines/show.html.erb
<%- model_class = Medicine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @medicine.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @medicine.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unit) %>:</strong></dt>
  <dd><%= @medicine.unit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:medicine_category_id) %>:</strong></dt>
  <dd><%= @medicine.medicine_category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:use) %>:</strong></dt>
  <dd><%= @medicine.use %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @medicine.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              medicines_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_medicine_path(@medicine), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              medicine_path(@medicine),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/medicines/update.html.erb
<h1>Medicines#update</h1>
<p>Find me in app/views/medicines/update.html.erb</p>

app/views/prescriptions/destroy.html.erb
<h1>Prescriptions#destroy</h1>
<p>Find me in app/views/prescriptions/destroy.html.erb</p>

app/views/prescriptions/edit.html.erb
<h1>Prescriptions#edit</h1>
<p>Find me in app/views/prescriptions/edit.html.erb</p>

app/views/prescriptions/index.html.erb
<h1>Prescriptions#index</h1>
<p>Find me in app/views/prescriptions/index.html.erb</p>

app/views/prescriptions/update.html.erb
<h1>Prescriptions#update</h1>
<p>Find me in app/views/prescriptions/update.html.erb</p>

app/views/shared/_error.html.erb
 <% flash.each do |key, value| %>
    <div id="error_explanation">
      <div class="alert alert-#{key}">
        <%= value unless value.blank? %>
      </div>
    </div>
  <% end %>

app/views/shared/_flash.html.erb
 <% flash.each do |key, value| %>
    <div id="error_explanation">
      <div class="alert alert-success ">
        <%= value unless value.blank? %>
      </div>
    </div>
  <% end %>